name: jira-diagram
channels:
  - conda-forge
dependencies:
  - python=3.11
  - graphviz                # provides dot binary
  - python-graphviz         # Python binding (conda)
  - lxml
  - pip
  - pip:
    - requests==2.32.4
    - graphviz==0.21
    - graphviz2drawio==1.1.0
    - networkx==3.4.2
    - xmltodict==0.14.2
    - pygraphviz==1.14
    - numpy==2.2.6
